### PR TITLE
Add production env to ui build

### PR DESCRIPTION
**Pull request by ekelen**
- Rm typo node package
- Remove references to -1.png
- Hardcode prod server address in Dockerfile, unless @eskombro has a better idea :)

Edit: Script added, see latest commit

### CODE REVIEW

**Comment by eskombro** [comment]
So, @eskombro 's idea:

Shell script:
- Find the public IP for the current server
- Set env variables on the system (URLs)
- Run docker-compose

Modify docker-compose to get env variables from system

Add env variable for allowed hosts in server (Go server package)

:)

**Review by eskombro — DISMISSED** [review]

**Comment by eskombro** [comment]
Could be a Makefile also, as @ekelen suggests

**Comment by ekelen** [comment]
✅ Script written

**Review by eskombro — APPROVED** [review]
Gut!!!

**Pull request merged**
